import type { Metadata } from "next";
import "./globals.css";
import ThemeRegistry from "./component/ThemeRegistry";
import StaticHeader from "./component/header/staticHeader";
import Navbar from "./component/navbar";
import Footer from "./component/footer/footer";
import Container from "@mui/material/Container";

export const metadata: Metadata = {
  title: "Next App MUI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeRegistry>
        <body>
          <StaticHeader />
          <Navbar />
          <Container maxWidth="xl">{children}</Container>
          <Footer />
        </body>
      </ThemeRegistry>
    </html>
  );
}
